# packages in environment at /Users/nagashayanaramamurthy/anaconda/envs/myenv:
#
certifi                   2016.2.28                py36_0  
click                     6.7                      py36_0  
flask                     0.12.2                   py36_0  
Flask-API                 1.0                       <pip>
flask-cors                3.0.3                    py36_0  
Flask-SQLAlchemy          2.3.2                     <pip>
itsdangerous              0.24                     py36_0  
jinja2                    2.9.6                    py36_0  
markupsafe                1.0                      py36_0  
openssl                   1.0.2l                        0  
pip                       9.0.1                    py36_1  
python                    3.6.2                         0  
readline                  6.2                           2  
setuptools                36.4.0                   py36_1  
six                       1.10.0                   py36_0  
SQLAlchemy                1.1.14                    <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
werkzeug                  0.12.2                   py36_0  
wheel                     0.29.0                   py36_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0  
